apiVersion: v1
entries:
  nuodb-cp-crd:
  - apiVersion: v2
    appVersion: 2.3.2
    created: "2024-02-20T19:13:21.222775692Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: 65d236849ff609298044f9be26ab2aa19688bf045d9d8404a4d8859d15505a51
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.2/nuodb-cp-crd-2.3.2.tgz
    version: 2.3.2
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2023-12-18T18:00:23.775714727Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: 7a787630986e206b31c83722696eae802236149962675118c2fcb5d3bc130ce1
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.1/nuodb-cp-crd-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2023-12-15T21:50:09.951723164Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: b41169598a0732c4a49cefc1d805538f6bddfeab5b35f3a07c3c35c32e578aa6
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.0/nuodb-cp-crd-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2023-10-04T11:57:39.568449087Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: 768371a04448a6c5e32558a1e0291314aba12a8e03b193af66fdddd5fc536d8d
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.1/nuodb-cp-crd-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2023-10-02T13:19:31.371792932Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: 5e0a932fa75cf8e3926d2267bbaa9fbd575fc6cf219d43c93a0e1141f205b59a
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.0/nuodb-cp-crd-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.1
    created: "2023-09-05T19:11:03.784765103Z"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: fc2221c9980e0dfdb305f184c87d80843bf93bb221ccaef668d9a61c458917ad
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.1/nuodb-cp-crd-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2023-08-30T21:02:22.82049-04:00"
    description: NuoDB Control Plane custom resource definitions (CRDs)
    digest: b6d90dc8a2109a4c91e25e17435da42a56fbeb13761d7558dea1b6c9bb2c7d5e
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-crd
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - operator
    - crd
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-crd
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.0/nuodb-cp-crd-2.1.0.tgz
    version: 2.1.0
  nuodb-cp-doc:
  - apiVersion: v2
    appVersion: 2.3.2
    created: "2024-02-20T19:13:21.223518606Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: b1daee1c5ab9a27e53721a61dcc35ebe2612386348bcac322ebaa22f3f7ce5b0
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.2/nuodb-cp-doc-2.3.2.tgz
    version: 2.3.2
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2023-12-18T18:00:23.776474137Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: 942259c6af626ea1e7ac6fe8360868f44487c3aedf40d26f38c44fcc66b6685e
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.1/nuodb-cp-doc-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2023-12-15T21:50:09.952501624Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: 1a5d3f9b5a789bdf1a2c2e247c61a460eecbc73e24f0f2b98186d8fecde17466
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.0/nuodb-cp-doc-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2023-10-04T11:57:39.569350353Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: ffd4d2583d17f1efb51148fd1dcddf6d7de6eff4421106368f50c137c101a5b1
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.1/nuodb-cp-doc-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2023-10-02T13:19:31.372664986Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: ba1b30890a8c882df554f75701390eb1536182ffe7fb8d010c238bec35364fec
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.0/nuodb-cp-doc-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.1
    created: "2023-09-05T19:11:03.785632981Z"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: 6f0e84097c9b360dfc14735b3e2511cf47dd1e5d3ac1dd72b4a76063e6eaa3df
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.1/nuodb-cp-doc-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2023-08-30T21:02:22.822482-04:00"
    description: Interactive documentation for the NuoDB Control Plane REST API
    digest: b0aa0ac6c1fac8f6589f5cfbdc4291b9408038f64f3006636dc71b5719b97e07
    name: nuodb-cp-doc
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.0/nuodb-cp-doc-2.1.0.tgz
    version: 2.1.0
  nuodb-cp-operator:
  - apiVersion: v2
    appVersion: 2.3.2
    created: "2024-02-20T19:13:21.224058743Z"
    description: NuoDB Control Plane Operator
    digest: 591c3ff88c6a7198806c0f8371d32824bdaab21dbf060bd04a8e2c7e5b5086cc
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.2/nuodb-cp-operator-2.3.2.tgz
    version: 2.3.2
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2023-12-18T18:00:23.77706968Z"
    description: NuoDB Control Plane Operator
    digest: 39717aca7e14c1e49ec82e026e2460b5185e1a4b324c617ba94b4389dd27a835
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.1/nuodb-cp-operator-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2023-12-15T21:50:09.953083538Z"
    description: NuoDB Control Plane Operator
    digest: 192daebd74a13f2371ae4c917e1a795e8d21cdd781d36e4c2e151064f01f30df
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.0/nuodb-cp-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2023-10-04T11:57:39.570109808Z"
    description: NuoDB Control Plane Operator
    digest: beba8990606d46f9ad12509a70bcb72b1c158062b4443b25c00081c1929d565d
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.1/nuodb-cp-operator-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2023-10-02T13:19:31.373406831Z"
    description: NuoDB Control Plane Operator
    digest: fa9f639f0abd82c48649259cf71cbd53cd69a0ca12e7456604400cdc4ded1b85
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.0/nuodb-cp-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.1
    created: "2023-09-05T19:11:03.786388449Z"
    description: NuoDB Control Plane Operator
    digest: c9d99b1393f04b616396f6ef68160010aeb84f33e1bd6c8cf0e099e02b5e14ce
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.1/nuodb-cp-operator-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2023-08-30T21:02:22.823313-04:00"
    description: NuoDB Control Plane Operator
    digest: 451f9288222b3384d18d588e6d2fa0400ef7cff4dbf4f638b5fde5da1cca7195
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-operator
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - controller
    - operator
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-operator
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.0/nuodb-cp-operator-2.1.0.tgz
    version: 2.1.0
  nuodb-cp-rest:
  - apiVersion: v2
    appVersion: 2.3.2
    created: "2024-02-20T19:13:21.224558634Z"
    description: NuoDB Control Plane REST service
    digest: 6554bd06f42fb427af8db13222a45a5ed9ad2b913b53b4bd016f0945ea849360
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.2/nuodb-cp-rest-2.3.2.tgz
    version: 2.3.2
  - apiVersion: v2
    appVersion: 2.3.1
    created: "2023-12-18T18:00:23.777621531Z"
    description: NuoDB Control Plane REST service
    digest: 6af96ec925ae5d425547157135a62f93b6d7643c150a92253f915fc22777153f
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.1/nuodb-cp-rest-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2023-12-15T21:50:09.953576967Z"
    description: NuoDB Control Plane REST service
    digest: 401f54b8482f03a49f9bc7c99a00b43cbf1f6542634292a44cd2b68b6948c7c4
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.3.0/nuodb-cp-rest-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.1
    created: "2023-10-04T11:57:39.570797758Z"
    description: NuoDB Control Plane REST service
    digest: d5374d669d2991be317602677fc01a058bf99ac34aeea988a1580d959694cee8
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.1/nuodb-cp-rest-2.2.1.tgz
    version: 2.2.1
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2023-10-02T13:19:31.374063372Z"
    description: NuoDB Control Plane REST service
    digest: b8a4bdb7c1e2aa8c252199c06c7d26d4178d401c39f2807d2b5702fcbe4ecc39
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.2.0/nuodb-cp-rest-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.1
    created: "2023-09-05T19:11:03.786986203Z"
    description: NuoDB Control Plane REST service
    digest: 99029a2d618351ab715b4f1cf1d880be9b16d8aaf43ce28f65133bb0e2410688
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.1/nuodb-cp-rest-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2023-08-30T21:02:22.824016-04:00"
    description: NuoDB Control Plane REST service
    digest: 598b5dce4474b9941e3fce660eeefd4cc51862b724ed1682a65d161c5d3e5d2e
    home: https://github.com/nuodb/nuodb-control-plane/charts/nuodb-cp-rest
    icon: https://raw.githubusercontent.com/nuodb/nuodb-helm-charts/master/images/nuodb.svg
    keywords:
    - nuodb
    - rest
    maintainers:
    - email: support@nuodb.com
      name: NuoDB
    name: nuodb-cp-rest
    type: application
    urls:
    - https://github.com/nuodb/nuodb-cp-releases/releases/download/v2.1.0/nuodb-cp-rest-2.1.0.tgz
    version: 2.1.0
generated: "2024-02-20T19:13:21.221506663Z"
